### ISSUE TITLE
Clickhouse勉強会:docker-compose.yml

### ISSUE THREAD

**Issue by drillan** [fin-py/events#3]
ローカルPCで再現できる環境を用意する

Redashの `docker-compose.yml` に [yandex/clickhouse-server](https://hub.docker.com/r/yandex/clickhouse-server/) Clickhouseを追加する

**Comment by drillan** [comment]
とりあえず、これで動いた

```yaml
version: '2'
x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: redash.env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.5-alpine
    env_file: redash.env
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /mnt/mysql/var:/var/lib/mysql
      - /mnt/mysql/etc:/etc/mysql/conf.d
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - /mnt/clickhouse/var:/var/lib/clickhouse
      - /mnt/clickhouse/etc:/etc/clickhouse-server/users.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
```

別途、ローカル用に作り直したものをリポジトリにpushする
